import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Practice | Tailwind",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="min-w-screen min-h-screen flex flex-col justify-center items-center">{children}</body>
        </html>
    );
}
